### ISSUE TITLE
Could not find a package configuration file

### ISSUE THREAD

**Issue by aaallami** [sharemind-sdk/standalone-demo#1]
Hello, 
I was trying to run the standalone-demo on the Sharemind MPC SDK & Emulator. I got the following error:
CMake Error at CMakeLists.txt:37 (FIND_PACKAGE):
  By not providing "FindSharemindLibController.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "SharemindLibController", but CMake did not find one.

  Could not find a package configuration file provided by
  "SharemindLibController" with any of the following names:

    SharemindLibControllerConfig.cmake
    sharemindlibcontroller-config.cmake

  Add the installation prefix of "SharemindLibController" to
  CMAKE_PREFIX_PATH or set "SharemindLibController_DIR" to a directory
  containing one of the above files.  If "SharemindLibController" provides a
  separate development package or SDK, be sure it has been installed.
I have no idea how to fix this.
I appreciate any help.
Best regards
ALI

**Comment by druid** [comment]
Unfortunately, you cannot use standalone-demo with the Sharemind MPC Emulator provided in the SDK.

The Sharemind MPC SDK is meant for developing SecreC programs and the Emulator can be used to test this bytecode (.sb files). This bytecode can then be deployed on the real Sharemind Application Server without any modifications. However, the Emulator does not provide an interface for client applications (SharemindLibController). To access SharemindLibController in order to build custom client applications, you'll need a licensed Sharemind Application Server, either a commercial or an academic one.

I apologise for taking so long to reply.
